# Generated by Django 5.0.4 on 2024-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='_singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='call',
            name='_singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='_singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='information',
            name='_singleton',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
