# Generated by Django 5.0.4 on 2024-04-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about__singleton_call__singleton_footer__singleton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='_singleton',
        ),
        migrations.RemoveField(
            model_name='call',
            name='_singleton',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='_singleton',
        ),
        migrations.RemoveField(
            model_name='information',
            name='_singleton',
        ),
    ]
